export const SHOW_REMOVE_BUTTON = "SHOW_ROMOVE_BUTTON";
export const HIDE_REMOVE_BUTTON = "HIDE_ROMOVE_BUTTON";
export const REMOVE_FROM_MY_LIST = "REMOVE_FROM_MY_LIST";
export const SHOW_ADD_BUTTON = "SHOW_ADD_BUTTON";
export const HIDE_ADD_BUTTON = "HIDE_ADD_BUTTON";
export const ADD_TO_MY_LIST = "ADD_TO_MY_LIST";
